[build]
# Command to build the Go application
cmd = "go build -o ./tmp/main ."

# Pre-build command:
# this command finds changed Go files, groups them by directory,
# and runs golangci-lint once per directory for the changed files.
pre_cmd = [
  "make lintFix",
  "go test ./... "
]

# Directory for the build output
bin = "tmp/main"
# full_bin = "./tmp/main go"

# File extensions to watch for changes and trigger a build
include_ext = ["go", "tmpl", "html"]

# Directories and files to exclude from the build process
exclude_dir = ["tmp", "vendor", "node_modules"]
